name: CI/CD Pipeline Workflow

on:
  push:
    branches:
      - main  # Specify the branches you want to trigger the workflow for (e.g., main)

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: read 
      id-token: write 
      issues: write 
      pull-requests: write
    
    steps:
      - run: echo "Starting CI/CD workflow. status ${{ job.status }}"
      
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"

  TruffleHog:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: bash
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0 
      
      - name: TruffleHog OSS
        id: trufflehog
        uses: trufflesecurity/trufflehog@v1
        continue-on-error: true
        with:
          path: ./
          base: "${{ github.event.repository.default_branch }}"
          head: HEAD
          extra_args: --debug --only-verified

      - name: Fail the pipeline if secrets are found
        if: steps.trufflehog.outcome == 'failure'
        run: |
          echo "TruffleHog found secrets. Failing the build."
          exit 1  # Force failure of the job if secrets are detected

