name: CI/CD Pipeline Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request targeting main branch

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow. status ${{ job.status }}"

      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure entire history is fetched for proper scanning

      - name: Install dependencies
        run: npm ci  # Install dependencies (corrected the npm command)

      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"

  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      # Checkout code to ensure TruffleHog has access to the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for scanning

      # Scan the entire branch using TruffleHog
      - name: Scan entire branch for secrets
        id: trufflehog_scan
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""  # Empty base to scan from the beginning of the branch
          head: ${{ github.ref_name }}  # Current branch reference
          extra_args: --results=verified,unknown  # Only include verified and unknown secrets

      # Check if TruffleHog scan failed (i.e., secrets were found) and fail the build
      - name: Fail the build on secret detection
        if: steps.trufflehog_scan.outcome == 'failure'  # If secrets are found
        run: |
          echo "TruffleHog detected secrets. Failing the build."
          exit 1  # Force failure
