name: CI/CD Pipeline Workflow
on: [push]
jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow. status ${{ job.status }}"
      - name: Check out repo
        uses: actions/checkout@v4
      # - run: echo "Status: ${{ job.status }}"
      - name: Install dependencies 
        run: npm ci install
      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"