name: CI/CD Pipeline Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request targeting main branch

jobs:
  Scan-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI/CD workflow. status ${{ job.status }}"
      
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure entire history is fetched for proper scanning

      - name: Install dependencies
        run: npm ci  # Install dependencies (corrected the npm command)
      
      - run: echo "Pipeline run successfully. Have a great day! status ${{ job.status }}"

  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      # Checkout code to make sure TruffleHog has access to the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for scanning

      - name: scan-push
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
      
      # Run TruffleHog to scan for secrets
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main  # Use the latest version from the main branch
        with:
          extra_args: --results=verified,unknown  # Scan for verified and unknown secrets
      
      # Fail the workflow if secrets are detected
      - name: Fail on secrets detection
        if: failure()  # If the previous step fails (i.e., secrets are detected)
        run: |
          echo "TruffleHog found secrets. Failing the build."
          exit 1  # Force the workflow to fail
